// <auto-generated />
using Dalily.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dalily.Migrations
{
    [DbContext(typeof(DalilyContext))]
    [Migration("20230611153231_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dalily.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("End_WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook_page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeographicalLocation_GPS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram_page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedin__page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start_WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTok_page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter__page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whatsapp_business_account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkplaceCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkplaceGovernorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkplaceResidentialArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTube_page")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
